#!/bin/bash
if [ -z "$1" ]
then
	echo "Usage: newmod module_name"
else
	mkdir $1
	chmod 775 $1
	f=`dirname $0`
	cp $f/template.module $1/$1.module
	cp $f/template.info $1/$1.info
  cp $f/template.install $1/$1.install
  cp $f/CHANGELOG.txt $1/CHANGELOG.txt
	cp $f/LICENSE.txt $1/LICENSE.txt
  cp $f/README.md $1/README.md
  cp $f/.gitignore $1/.gitignore
	cp $f/.codeclimate.yml $1/.codeclimate.yml
  cp -R $f/css $1/css
  cp -R $f/js $1/js
	cd $1
fi
